# Generated by Django 4.1.3 on 2022-12-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modeles',
            new_name='Mobiles',
        ),
    ]
